### ISSUE TITLE
Interactive map of test centers in Germany

### ISSUE THREAD

**Issue by adaline** [Kavakuo/LabHive#14]
We have the labs with lat/long already in the DB.

We would like to have a map showing these on the front page.

Perhaps a new API endpoint with just the lat/long and name?
Then we can ask them to login to see contact details etc.

**Comment by SethGreylyn** [comment]
After some initial research, it looks like there is no current, reliable implementation of a Google Maps plugin (the clearest one I could find is [begging](https://github.com/xkjyeah/vue-google-maps) for maintainers, but there is a *very* promising Leaflet [library](https://vue2-leaflet.netlify.com/), which should suit our needs well.
