### ISSUE TITLE
Search Result View

### ISSUE THREAD

**Issue by Kavakuo** [Kavakuo/LabHive#23]
Branch for the search is `profile_search2`

I am still not happy with the look and feel of the search results. Not even sure if a `b-card` is the right UI Element to display a result.

My thoughts are that the results on the list view should be as small as possible, to get as quick as possible an overview over the search results. Basicially like a table. But a table is always a pain on mobile devices/small screens. To get more details (like the contact information) for a search result, maybe a modal view is suited, displaying the address and contact information? We could also embed a map into the modal view to show the location.

Let's discuss it here, if you have different thoughts :)

**Comment by adaline** [comment]
Sounds good, we can hide some fields in an actual table on mobile - so not too much of an issue, lets try it!

Modal might actually be the problem on mobile - if the endless cookie modals are anything to go by, again have to try it out :)

**Comment by Kavakuo** [comment]
Have a look at Figma, for the most recent mockup

**Comment by Kavakuo** [comment]
Fixed with e79ce8ddd29dab4ec226dc443c46af5bbe157fce
