### ISSUE TITLE
Check boxes for Qualification section in Volunteer registration

### ISSUE THREAD

**Issue by topialla** [Kavakuo/LabHive#39]
The way the backend is defined (and I believe we had this in the past already?) we should have check boxes for the different "Qualifications" listed, instead of radio buttons.

I now just saw in the answer, that it doesn't (anymore?) return an array, which it shouldn't given that there are radio buttons currently...

**Comment by Kavakuo** [comment]
Was fixed with 6081f0eac8b59cfbc267acb0d598ca137b3bcd34
