### ISSUE TITLE
Improve translations

### ISSUE THREAD

**Issue by Kavakuo** [Kavakuo/LabHive#43]
The following files still need to be localized:

- [x] [labshare-client/src/localization.js](https://github.com/Kavakuo/LabHive/blob/localization-improvements/labshare-client/src/localization.js)
- [x] [labshare-client/src/components/CheckboxGroup.vue](https://github.com/Kavakuo/LabHive/blob/localization-improvements/labshare-client/src/components/CheckboxGroup.vue)
- [x] [labshare-client/src/backend/mail/localization.ts (Mail-Templates)](https://github.com/Kavakuo/LabHive/blob/localization-improvements/labshare-client/src/backend/mail/localization.ts)

**Comment by topialla** [comment]
all translations are done. Please have a look @SethGreylyn

**Comment by topialla** [comment]
@SethGreylyn went through this already, I think.
